AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with EventBridge trigger permissions
Transform: AWS::Serverless-2016-10-31

Parameters:
  CronSchedule:
    Description: "Cron expression for the EventBridge rule to trigger the Lambda function"
    Type: String

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaLoggingAndSES
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/stock-tracker:*
              - Effect: Allow
                Action: ses:SendEmail
                Resource: "*"

  StockTrackerLambdaFnc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stock-tracker
      Runtime: nodejs22.x
      Handler: src/index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 20
      CodeUri: ../stock-tracker.zip
      MemorySize: 200
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref CronSchedule
            Name: StockTrackerSchedule
            Description: "Trigger stock-tracker function Tuesday to Saturday at 6:10 AEST"
            Enabled: true
